name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c595409d89817b6357c19ff804a5fe89ccd01417da50a4cac7d5c55c95aed90a"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
