name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "196ecebdac224f0c46f50a88d3a709da87ce2a4b1d8db20fe4b6edea73f30f0a"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
