name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "507c2c418263c0eafc36c00e18e6c30338e319e01b88ee425fce19940c9c66ff"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
