name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d524596be14255f0933cb12f41184d94bc322d8a3afb88de857eb87ee657d5f"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
