name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe7baac88115e26520ed7537e5a91e6f9a321b4d20c8e7b6fa5697b289c5516f"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
