name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "184a346da359bd79157f7dba88e5ae2a6aa95f8f69423ad9e37a2793936eaf36"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
