name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac11e0e6231cac3b1f6a79e75070f4cad5ab38e2a37093a31d6e98fb8dcbe44"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
