name = "Applied Energistics 2"
filename = "appliedenergistics2-fabric-8.4.0-alpha.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3487/384/appliedenergistics2-fabric-8.4.0-alpha.3.jar"
hash-format = "murmur2"
hash = "3946059950"

[update]
[update.curseforge]
file-id = 3487384
project-id = 223794
