name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-1.2.5-release.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3512/109/AE2WTLib-1.2.5-release.jar"
hash-format = "murmur2"
hash = "3379194314"

[update]
[update.curseforge]
file-id = 3512109
project-id = 459929
