name = "Applied Energistics 2"
filename = "appliedenergistics2-fabric-8.3.0-alpha.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3331/816/appliedenergistics2-fabric-8.3.0-alpha.3.jar"
hash-format = "murmur2"
hash = "2005305389"

[update]
[update.curseforge]
file-id = 3331816
project-id = 223794
