name = "GeckoLib [FABRIC]"
filename = "geckolib-fabric-1.16.5-3.0.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/383/geckolib-fabric-1.16.5-3.0.40.jar"
hash-format = "murmur2"
hash = "1833272281"

[update]
[update.curseforge]
file-id = 3343383
project-id = 398667
