name = "Golden Hoppers"
filename = "goldenhoppers-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3275/241/goldenhoppers-1.0.2.jar"
hash-format = "murmur2"
hash = "3650200457"

[update]
[update.curseforge]
file-id = 3275241
project-id = 442268
