name = "Winged"
filename = "winged-1.16.5-2.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/616/winged-1.16.5-2.1.4.jar"
hash-format = "murmur2"
hash = "2551000452"

[update]
[update.curseforge]
file-id = 3345616
project-id = 381349
